In [4]:
import torch
import numpy as np

a = torch.tensor([[1,2],[3,4]])
a

tensor([[1, 2],
        [3, 4]])

In [5]:
b = a.repeat_interleave(2,dim=0)
b

tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])

In [8]:
c = a.repeat(2,1)
c

tensor([[1, 2],
        [3, 4],
        [1, 2],
        [3, 4]])

In [13]:
result = torch.cat([b,c],dim=1)
result.view(2,2,-1)

tensor([[[1, 2, 1, 2],
         [1, 2, 3, 4]],

        [[3, 4, 1, 2],
         [3, 4, 3, 4]]])